services:
  sumatywny-api:
    build: .
    container_name: sumatywny-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: sumatywny
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  mongodb:
    container_name: mongo-db
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"