services:
  sumatywny-api:
    build: .
    ports:
      - "3333:3333" # API 
      - "5555:5555" # Prisma Studio
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env.docker
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: sumatywny
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - "27018:27017"