services:
  sumatywny-api:
    build: .
    ports:
      - "3333:3333" # API 
      - "5555:5555" # Prisma Studio
    depends_on:
      - postgres
      - mongo
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: sumatywny
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"